name: Build Static Binaries
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt-get install -y yasm
      - name: Build
        run: make
