name: Build Static Binaries
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Dependencies
        run: sudo apt-get install -y yasm auto{gen,conf,make}
      - name: Build
        run: make
